# Generated by Django 4.0.8 on 2022-11-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktuAkad', models.DateTimeField()),
                ('mahar', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=100)),
                ('diperiksa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Istri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nomorKtp', models.CharField(max_length=16, unique=True)),
                ('tanggalLahir', models.DateField()),
                ('alamat', models.CharField(max_length=255)),
                ('pekerjaan', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('1', 'Perawan'), ('2', 'Janda')], default=1, max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/perempuan')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penghulu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nomorKtp', models.CharField(max_length=16, unique=True)),
                ('tanggalLahir', models.DateField()),
                ('alamat', models.CharField(max_length=255)),
                ('pekerjaan', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('1', 'Jejaka'), ('2', 'Duda')], default=1, max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/laki')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pihak', models.CharField(choices=[('1', 'Suami'), ('2', 'Istri')], max_length=1)),
                ('no_ktp', models.CharField(max_length=16, unique=True)),
                ('hubungan', models.CharField(choices=[('1', 'Bapak'), ('2', 'Ibu'), ('3', 'Wali')], max_length=1)),
                ('nama', models.CharField(max_length=100)),
                ('tempatLahir', models.CharField(max_length=50)),
                ('tanggalLahir', models.DateField()),
                ('agama', models.CharField(max_length=20)),
                ('pekerjaan', models.CharField(max_length=50)),
                ('meninggal', models.BooleanField(default=False)),
                ('akad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.akad')),
            ],
        ),
        migrations.AddField(
            model_name='akad',
            name='istri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.istri'),
        ),
        migrations.AddField(
            model_name='akad',
            name='penghulu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.penghulu'),
        ),
        migrations.AddField(
            model_name='akad',
            name='suami',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.suami'),
        ),
    ]
