# Generated by Django 4.0.8 on 2022-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='akad',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
