# Generated by Django 4.0.8 on 2022-11-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_istri_nomorktp_alter_suami_nomorktp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='istri',
            old_name='alamat',
            new_name='alamatIstri',
        ),
        migrations.RenameField(
            model_name='istri',
            old_name='foto',
            new_name='fotoIstri',
        ),
        migrations.RenameField(
            model_name='istri',
            old_name='nama',
            new_name='namaIstri',
        ),
        migrations.RenameField(
            model_name='istri',
            old_name='nomorKtp',
            new_name='nomorKtpIstri',
        ),
        migrations.RenameField(
            model_name='istri',
            old_name='pekerjaan',
            new_name='pekerjaanIstri',
        ),
        migrations.RenameField(
            model_name='istri',
            old_name='status',
            new_name='statusIstri',
        ),
        migrations.RenameField(
            model_name='istri',
            old_name='tanggalLahir',
            new_name='tanggalLahirIstri',
        ),
        migrations.RenameField(
            model_name='suami',
            old_name='alamat',
            new_name='alamatSuami',
        ),
        migrations.RenameField(
            model_name='suami',
            old_name='foto',
            new_name='fotoSuami',
        ),
        migrations.RenameField(
            model_name='suami',
            old_name='nama',
            new_name='namaSuami',
        ),
        migrations.RenameField(
            model_name='suami',
            old_name='nomorKtp',
            new_name='nomorKtpSuami',
        ),
        migrations.RenameField(
            model_name='suami',
            old_name='pekerjaan',
            new_name='pekerjaanSuami',
        ),
        migrations.RenameField(
            model_name='suami',
            old_name='status',
            new_name='statusSuami',
        ),
        migrations.RenameField(
            model_name='suami',
            old_name='tanggalLahir',
            new_name='tanggalLahirSuami',
        ),
    ]
