# Generated by Django 4.0.8 on 2022-11-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_akad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='istri',
            name='tempatLahirIstri',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suami',
            name='tempatLahirSuami',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
