# Generated by Django 4.0.8 on 2022-11-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_istri_tempatlahiristri_suami_tempatlahirsuami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istri',
            name='tempatLahirIstri',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='suami',
            name='tempatLahirSuami',
            field=models.CharField(default='', max_length=50),
        ),
    ]
