# Generated by Django 4.0.8 on 2022-11-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_istri_tempatlahiristri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='akad',
            name='waliNikah',
            field=models.CharField(default='', max_length=50),
        ),
    ]
