# Generated by Django 4.0.8 on 2022-11-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_akad_walinikah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akad',
            name='waliNikah',
        ),
    ]
