# Generated by Django 4.0.8 on 2022-11-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_akad_jamakad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akad',
            name='jamAkad',
            field=models.TimeField(null=True),
        ),
    ]
