# Generated by Django 4.0.8 on 2022-11-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_akad_jamakad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akad',
            name='waktuAkad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
