# Generated by Django 4.0.8 on 2022-11-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_akad_waktuakad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akad',
            name='jamAkad',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='akad',
            name='waktuAkad',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='istri',
            name='tempatLahirIstri',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='suami',
            name='tempatLahirSuami',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wali',
            name='no_ktp',
            field=models.CharField(max_length=16),
        ),
    ]
