# Generated by Django 4.0.8 on 2022-11-22 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0015_alter_akad_jamakad_alter_akad_waktuakad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akad',
            name='penghulu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.penghulu'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLengkap', models.CharField(max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
