# Generated by Django 4.0.8 on 2022-11-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_akad_penghulu_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akad',
            options={'ordering': ['created']},
        ),
    ]
